apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: backup-test-topic
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 3
  configs:
    cleanup.policy: delete
    retention.ms: "604800000"
  kafkaClusterRef:
    name: kafka
