apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: backup-test-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: "604800000"
