apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-backup-operator
  namespace: confluent
  labels:
    app.kubernetes.io/name: kafka-backup-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-backup-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-backup-operator
        app.kubernetes.io/component: controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kafka-backup-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: operator
          image: ghcr.io/osodevops/kafka-backup-operator:latest
          imagePullPolicy: Never
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            - name: RUST_LOG
              value: "warn,kafka_backup_operator=info,kafka_backup_core=warn"
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: kafka-backup-storage
              mountPath: /data/kafka-backup-storage
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: kafka-backup-storage
          persistentVolumeClaim:
            claimName: kafka-backup-storage
        - name: tmp
          emptyDir: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
